# Generated by Django 3.2 on 2022-05-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220504_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fw',
            field=models.CharField(db_column='Featured works', max_length=100, null=True),
        ),
    ]
